name: chainsop CI
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: kquick
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: build
        shell: bash
        run: nix build github:${{ github.repository }}/${{ github.sha }}#chainsop
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v20
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v12
        with:
          name: kquick
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: doc
        shell: bash
        run: nix build github:${{ github.repository }}/${{ github.sha }}#chainsop.doc
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: result-doc

  deploy:
    needs: doc
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
